#!/bin/sh

# create rcouch group only if it doesn't already exist
getent group rcouch >/dev/null 2>&1
if [ $? -ne 0 ]; then
        groupadd rcouch
fi

# create rcouch user only if it doesn't already exist
getent passwd rcouch >/dev/null 2>&1
if [ $? -ne 0 ]; then
        useradd -g rcouch -d /opt/rcouch rcouch
        usermod -c "rcouch server" rcouch
fi

